export type TransactionStatus =
  | 'draft'
  | 'pending'
  | 'approved'
  | 'posted'
  | 'confirmed'
  | 'ready'
  | 'shipped'
  | 'delivered'
  | 'received'
  | 'closed'
  | 'cancelled'
  | 'void'
  | 'rejected'

export type MasterDataStatus = 'active' | 'inactive'

export type DocumentActionKey =
  | 'create'
  | 'edit'
  | 'detail'
  | 'activate'
  | 'deactivate'
  | 'approve'
  | 'post'
  | 'void'
  | 'cancel'
  | 'confirm'
  | 'close'
  | 'send'
  | 'accept'
  | 'reject'
  | 'issue'
  | 'ready'
  | 'ship'
  | 'deliver'
  | 'receive'
  | 'submit'
  | 'refund'
  | 'finalize'
  | 'counted'
